### ISSUE TITLE
"Turn on exposure notifications" tile is not redirecting when "Push notifications are off" is in the menu

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#519]
Environment : 
Pixel 3a, Android 10, v25 from Play Store

Scenario : 
- Install app but click on "Cancel" when prompted to turn on EN
- Home screen should have the "COVID Alert is off" screen
- Now go to your phone settings and turn off push notifications for the app
- Re-open the app
- Open menu, you should see a tile "Turn on EN" and a tile "Push notifications are off"
- Click on "Turn on EN"

Expected : 
A popup should be displayed to propose to the user to turn on EN

Issue : 
Nothing happens. The popup is not triggered.
Note : this happens only when both tiles are displayed at the same time. Push notifications tile is redirecting as expected.

![Screenshot (Jul  7, 2020 19_41_29)](https://user-images.githubusercontent.com/47008295/86869586-adf93900-c08b-11ea-858e-94220961f8a2.png)

**Comment by srepussard** [comment]
From the same scenario, when back on home screen, the button "Enable COVID Alert" is also not redirecting anywhere. Please fix as well.

**Comment by JuliannaR** [comment]
@smcmurtry is this part of the issue we were addressing with turning on the service?

**Comment by JuliannaR** [comment]
@timarney are you looking to confirm the issue yourself or for followup?

**Comment by srepussard** [comment]
I tested again on Pixel 3a, Android 10, v33 from Play Store and I confirm that this issue is still reproducible

**Comment by nickmly** [comment]
Tested on Essential Phone, Android 10, v34. This is what happened:
- Installed app from Play store and hit 'Cancel' when prompted for permissions
- Closed app, turned off push notifications in settings
- Re-opened app, I was prompted for turning on EN
- Clicked 'Cancel' again
- Clicking on 'Turn on exposure notification' button does not do anything

I will look into this and see if I can get it to work.

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, v46 from Play Store : **Passed**
- This has been fixed

**Comment by emilykuret** [comment]
@srepussard I am still having this bug on my Pixel 2XL on V46

**Comment by srepussard** [comment]
@emilykuret can you check if this is still reproducible on your Pixel 2XL with v51+?
It's still not reproducible for me on Pixel 3a v53

**Comment by timarney** [comment]
Confirm will @emilykuret that this appears to be fixes now.
